### PR TITLE
Add new VSCode toolbar icons

### PR DESCRIPTION
**Pull request by Pustur**
Hi,

Recently VSCode changed the toolbar icons so I thought I'll send you a PR to change them here as well.

I admit that **I did not test the code** so you should check that it works before merging it. That said, the changes are pretty simple so hopefully it will work without additional modifications.

### Info:

- Changed comments to link to the new icons
- `viewBox` seems to be consistent now (`0 0 24 24`)
- Some icons need an additional property `fillRule` in the `path` element, so I added it to the icons that needed it. If the icon doesn't have a fillRule property it will be  
`<path fillRule={undefined} d={…} />` and it will be ignored once rendered.
- The process I used was:
  - Get icons from vscode repository
  - Optimize them with http://petercollingridge.appspot.com/svg-editor using the `Extreme` setting
  - Optimize them further with https://imageoptim.com/mac
  - Extract the `path` / `viewBox` / `fill-rule` and copy it to the `icons.ts` file

### CODE REVIEW

**Comment by jschr** [comment]
Thanks for the PR @Pustur. Your changes are included in https://github.com/jschr/vscodethemes/pull/158. I adjusted the styles slightly and fixed a TS error, otherwise I used it as is! 

Appreciate the contrubution.

**Comment by jschr** [comment]
Relased in https://github.com/jschr/vscodethemes/pull/159

**Comment by Pustur** [comment]
Hey @jschr, 

Just letting you know that the VSCode team just announced that they have a [GitHub repository for their icons](https://github.com/microsoft/vscode-icons). Could be useful in the future.

Thanks for accepting the PR,
Loris

**Comment by jschr** [comment]
@Pustur definitely, thanks for letting me know!

**Pull request closed without merging**
