### PR TITLE
need to prevent default form submission behavior even on mobile devices

### LINKED ISSUE #179: Search not working on iOS
Searching seems to do nothing and url looks malformed after pressing enter on iOS.

image

### PR DESCRIPTION
**Pull request by ntrabue**
hopefully resolves #179

### CODE REVIEW

**Comment by jschr** [comment]
hey @ntrabue, thanks for the PR. I saw the discussion in the other issue.

Sorry about the lack of docs for contributing. Truth is I've started a rewrite vscodethemes hoping to make it easier for others to contribute but I just don't have much time to finish it right now.  

Since this change is frontend-only you don't need to mess around with AWS.

This should get you running locally:

1. From the repo locally: `cd frontend` 
2. Run locally against the production backend: 

```
ALGOLIA_SEARCH_KEY=fb233d35cbb3656ddeab014eb4bf3eb8 \
TF_VAR_algolia_app_id=4DSENNCE1V \
TF_VAR_algolia_index=production_themes \
yarn dev
```

**Comment by Fasani** [comment]
Great teamwork! This is what GitHub is all about!

@ntrabue was the info above enough to get it running locally? If you managed it, could I recommend you document the process on the README.md and open a second PR?

**Comment by ntrabue** [comment]
> Great teamwork! This is what GitHub is all about!
> 
> @ntrabue was the info above enough to get it running locally? If you managed it, could I recommend you document the process on the README.md and open a second PR?

Trying to get it to run locally today. I will keep you posted. Having xcode issues on my personal machine right now trying to get that resolved. Do I just create a .env file in the frontend directory or at root?

**Comment by Fasani** [comment]
Usually a `.env' file is in the root of a project.

**Comment by ntrabue** [comment]
Okay, I put the .env file at the root of my project. 

I had a hell of a time getting modules installed with yarn getting node-gyp errors. Turns out I was using node v12.x.x and downgrading to the node version specified in the .nvmrc file resolved that issue. 

However, after installing all of my modules successfully and trying to run the dev script in the frontend dir I get the following error and I'm not sure how to move forward: 
```
yarn run v1.22.10
$ ./run-server.sh
$ /Users/ntrabue/sites/vscodethemes/node_modules/.bin/ts-node -O '{"module": "commonjs"}' server.ts
UPDATE AVAILABLE The latest version of `next` is 9.5.5
> Using external babel configuration
> Location: "/Users/ntrabue/sites/vscodethemes/frontend/.babelrc"


 ERROR  Failed to compile with 2 errors                                                                                                                                 

 error  in ../types/static.ts

Module parse failed: Unexpected token (18:7)
You may need an appropriate loader to handle this file type.
| } from './runtime'
|
| export type ExtensionQueryResults = Static<typeof ExtensionQueryResultsRuntime>
| export type Extension = Static<typeof ExtensionRuntime>
| export type ScrapeExtensionsPayload = Static<

 @ ../types/index.ts 2:0-24
 @ ./components/ThemePreview/ThemePreview.tsx
 @ ./components/ThemePreview/index.tsx
 @ ./components/index.ts
 @ ./pages/_app.tsx
 @ multi ./pages/_app.tsx

 error  in ../theme-variables/index.ts

Module parse failed: Unexpected token (8:26)
You may need an appropriate loader to handle this file type.
| import * as Color from 'color'
|
| const transparent = (color: string, alpha: number) =>
|   color
|     ? Color(color)

 @ ./utils/withDefaultColors.ts 5:0-59
 @ ./components/ThemeRotator/ThemeRotator.tsx
 @ ./components/ThemeRotator/index.ts
 @ ./components/index.ts
 @ ./pages/_app.tsx
 @ multi ./pages/_app.tsx

(node:3075) DeprecationWarning: Module.chunks: Use Module.forEachChunk/mapChunks/getNumberOfChunks/isInChunk/addChunk/removeChunk instead
> Frontend ready on http://localhost:3000
```

After going to localhost:3000 I get the following error in the terminal and the page never loads:
```
express deprecated req.host: Use req.hostname instead server.ts:16:31
(node:3075) UnhandledPromiseRejectionWarning: Error: Cannot find module '/Users/ntrabue/sites/vscodethemes/frontend/build/build-manifest.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at _callee3$ (/Users/ntrabue/sites/vscodethemes/node_modules/next/dist/server/render.js:202:29)
    at tryCatch (/Users/ntrabue/sites/vscodethemes/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/ntrabue/sites/vscodethemes/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/ntrabue/sites/vscodethemes/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/ntrabue/sites/vscodethemes/node_modules/next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:12:30)
    at _next (/Users/ntrabue/sites/vscodethemes/node_modules/next/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
(node:3075) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3075) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Pull request merged**
